
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-win-x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Build
      run: ./buildWin.bat

    - name: Upload
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-win-x86
        path: ./bin/
